miscosas/home/api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('retrieve/', ListFeeders.as_view()),
    path('create/', CreateFeeder.as_view()),
]

miscosas/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('xml/', home_xml, name='home_xml'),
    path('feeders/', feeders, name='feeders'),
    path('feeders/<feeder_id>/', feeder, name='feeder'),
    path('items/', items, name='items'),
    path('items/<item_id>/', item, name='item'),
    path('users/', users, name='users'),
    path('users/<user_id>/', user, name='user'),
    path('info/', info, name='info'),
]

miscosas/miscosas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # rest api
    path('api/accounts/', include('accounts.api.urls')),
    path('api/home/', include('home.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miscosas/home/models.py
from django.contrib.auth.models import User
from django.db import models


class Feeder(models.Model):
    feeder = models.CharField(max_length=20)
    title = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    item_number = models.IntegerField()
    score = models.IntegerField(default=0)
    positive_score = models.IntegerField(default=0)
    negative_score = models.IntegerField(default=0)
    visible_status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-score']


class Item(models.Model):
    feed = models.ForeignKey(Feeder, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=True, null=True)
    link = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    score = models.IntegerField(default=0)
    positive_score = models.IntegerField(default=0)
    negative_score = models.IntegerField(default=0)
    embedded = models.CharField(max_length=255, blank=True)  # for only youtube

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-score']


class Comment(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    commented_item = models.ForeignKey(Item, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    createdAt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-createdAt']

miscosas/home/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from home.parser import *


class ListFeeders(APIView):

    def get(self, request):
        feedertitles = [feeder.title for feeder in Feeder.objects.all()]
        return Response(feedertitles)


class CreateFeeder(APIView):

    def post(self, request):
        feeder_name = request.POST['feeder']
        url = request.POST['url']
        if Feeder.objects.filter(link__iendswith=url).count() == 1:
            result = "exist"
            return Response(result)
        result = ""
        if feeder_name == "Youtube":
            url = "https://www.youtube.com/feeds/videos.xml?channel_id=" + url
            result = youtube_parser(url)
        elif feeder_name == "Reddit":
            url = "https://www.reddit.com/r/" + url + ".rss"
            result = subreddit_parser(url)
        return Response(result)

miscosas/home/views.py
import os

from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from django.shortcuts import render, redirect

from accounts.models import Profile
from miscosas.settings import BASE_DIR
from .parser import *
from .models import *


def home(request):
    if 'style' not in request.session:
        request.session['style'] = 'light'
    if 'font_size' not in request.session:
        request.session['font_size'] = '1rem'
    template_name = 'home/home.html'
    if request.is_ajax():
        flag = request.POST['flag']
        if flag == 'get_10_items':
            # get 10 items with the most score
            items_10 = 'empty'
            if Item.objects.count() != 0:
                items_10 = Item.objects.all()[:10].values('id', 'title', 'link', 'score', 'positive_score', 'negative_score')
                items_10 = list(items_10)
            return JsonResponse({"items_10": items_10})
        elif flag == 'get_feeders':
            feeder_values = 'empty'
            if Feeder.objects.filter(visible_status=True).count() != 0:
                feeder_values = Feeder.objects.filter(visible_status=True).values(
                    'id', 'title', 'link', 'item_number', 'score')
                feeder_values = list(feeder_values)
            return JsonResponse({"feeder_values": feeder_values})
        elif flag == 'create_feeder':
            feeder_name = request.POST['feeder']
            url = request.POST['url']
            if Feeder.objects.filter(link__iendswith=url).count() == 1:
                result = "exist"
                return JsonResponse({"result": result})
            result = ""
            if feeder_name == "Youtube":
                url = "https://www.youtube.com/feeds/videos.xml?channel_id=" + url
                result = youtube_parser(url)
            elif feeder_name == "Reddit":
                url = "https://www.reddit.com/r/" + url + ".rss"
                result = subreddit_parser(url)
            return JsonResponse({"result": result})
        elif flag == 'hide_feeder':
            feeder_id = request.POST['feeder_id']
            Feeder.objects.filter(id=feeder_id).update(visible_status=False)
            return JsonResponse({"result": "hide"})
        elif flag == 'show_feeder':
            feeder_id = request.POST['feeder_id']
            Feeder.objects.filter(id=feeder_id).update(visible_status=True)
            return JsonResponse({"result": "show"})
    context = {
        "current_menu": "home"
    }
    return render(request, template_name, context)


def home_xml(request):
    xml_path = os.path.join(BASE_DIR, 'home', 'templates', 'home', 'home.xml')
    items_10 = Item.objects.all()[:10]
    feeder_list = Feeder.objects.filter(visible_status=True)
    response = render(None, xml_path, {"items": items_10, "feeders": feeder_list})
    response['Content-Type'] = 'application/xml'
    return response


def items(request):
    template_name = 'home/items.html'
    item_list = Item.objects.all()
    context = {
        "current_menu": "items",
        "item_list": item_list
    }
    return render(request, template_name, context)


def handle_score(kind, updated_score, updated_positive_score, updated_negative_score):
    if kind == 'positive':
        updated_score += 1
        updated_positive_score += 1
    elif kind == 'negative':
        updated_score -= 1
        updated_negative_score += 1
    return updated_score, updated_positive_score, updated_negative_score


def item(request, item_id):
    template_name = 'home/item.html'
    if not Item.objects.filter(id=item_id).exists():
        return redirect('home:items')
    selected_item = Item.objects.filter(id=item_id)
    selected_item_first = selected_item.first()
    comments = Comment.objects.filter(commented_item=selected_item_first)
    context = {
        "current_menu": "items" + " : " + selected_item_first.title,
        "selected_item": selected_item_first,
        "comments": comments
    }
    if 'id' in request.session:
        # check voted status
        voted_status = False
        user_id = request.session['id']
        current_user = User.objects.get(id=user_id)
        profile = Profile.objects.filter(user=current_user)
        profile_first = profile.first()
        voted_item_ids = profile_first.voted_item_ids.split(",")
        voted_item_ids = list(filter(None, voted_item_ids))
        if str(item_id) in voted_item_ids:
            voted_status = True
        # check comment status
        commented_status = False
        if Comment.objects.filter(creator=current_user, commented_item=selected_item_first).exists():
            commented_status = True
        context['voted_status'] = voted_status
        context['commented_status'] = commented_status
        if request.is_ajax():
            flag = request.POST['flag']
            if flag == 'vote':
                kind = request.POST['kind']
                # update Profile table
                voted_item_ids.append(item_id)
                updated_voted_item_ids = ",".join(voted_item_ids)
                profile.update(voted_item_ids=updated_voted_item_ids)
                # update Item table
                updated_score = selected_item_first.score
                updated_positive_score = selected_item_first.positive_score
                updated_negative_score = selected_item_first.negative_score
                result = handle_score(kind, updated_score, updated_positive_score, updated_negative_score)
                selected_item.update(
                    score=result[0], positive_score=result[1], negative_score=result[2]
                )
                # update Feeder table
                updated_feeder = selected_item_first.feed
                selected_feeder = Feeder.objects.filter(id=updated_feeder.id)
                updated_feeder_score = updated_feeder.score
                updated_feeder_positive_score = updated_feeder.positive_score
                updated_feeder_negative_score = updated_feeder.negative_score
                result = handle_score(kind, updated_feeder_score, updated_feeder_positive_score,
                                      updated_feeder_negative_score)
                selected_feeder.update(
                    score=result[0], positive_score=result[1], negative_score=result[2]
                )
                return JsonResponse({"result": "ok"})
            elif flag == 'comment':
                text = request.POST['text']
                Comment.objects.create(
                    creator=current_user, commented_item=selected_item_first, description=text
                )
                return JsonResponse({"result": "ok"})
    return render(request, template_name, context)


def feeders(request):
    template_name = 'home/feeders.html'
    feeder_list = Feeder.objects.all()
    context = {
        "current_menu": "feeders",
        "feeder_list": feeder_list
    }
    return render(request, template_name, context)


def feeder(request, feeder_id):
    template_name = 'home/feeder.html'
    feed = Feeder.objects.filter(id=feeder_id).first()
    item_feed = Item.objects.filter(feed=feed)
    context = {
        "current_menu": "feeders" + " : " + feed.title,
        "feed_id": feed.id,
        "feed_title": feed.title,
        "feed_link": feed.link,
        "number_of_items": len(item_feed),
        "feed_visible_status": feed.visible_status,
        "item_feed": item_feed
    }
    return render(request, template_name, context)


def users(request):
    if 'id' not in request.session:
        return redirect('home:home')
    template_name = 'home/users.html'
    profiles = Profile.objects.all()
    profile_list = []
    for profile in profiles:
        user_id = profile.user.id
        username = profile.user.username
        photo = profile.photo
        voted_item_number = profile.voted_item_ids.split(",")
        voted_item_number = list(filter(None, voted_item_number))
        voted_item_number = len(voted_item_number)
        one = {
            'user_id': user_id, 'username': username, 'photo': photo, 'voted_item_number': voted_item_number
        }
        profile_list.append(one)
    context = {
        "current_menu": 'users',
        'profile_list': profile_list
    }
    return render(request, template_name, context)


def user(request, user_id):
    if 'id' not in request.session:
        return redirect('home:home')
    template_name = 'home/user.html'
    current_user = User.objects.get(id=user_id)
    profile = Profile.objects.filter(user=current_user)
    # get list of voted items
    voted_item_ids = profile.first().voted_item_ids.split(",")
    voted_item_ids = list(filter(None, voted_item_ids))
    voted_items = Item.objects.filter(id__in=voted_item_ids)
    # get list of commented items
    commented_items = Comment.objects.filter(creator=current_user)
    context = {
        "user_id": user_id,
        "current_menu": 'users',
        "current_user": current_user,
        "voted_items": voted_items,
        "commented_items": commented_items
    }
    if request.method == 'POST':
        file = request.FILES
        if 'photo' in file:
            if request.session['photo_url'] != 'images/default.png':
                past_photo = str(profile.first().photo)
                remove_photo_path = os.path.join(BASE_DIR, 'media', past_photo)
                os.remove(remove_photo_path)
            file = file['photo']
            fs = FileSystemStorage()
            fs.save(file.name, file)
            profile.update(photo=file)
            photo_url = Profile.objects.get(user=current_user).photo.url
            request.session['photo_url'] = photo_url
            return render(request, template_name, context)

miscosas/home/templates/home/feeder.html
{% extends 'root.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/global.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-secondary">Feeder Title: {{ feed_title }}</h4>
        </div>
        <div class="col-md-12">
            <h4 class="text-secondary">Feeder Link: <a href="{{ feed_link }}"
                                                       target="_blank">{{ feed_link }}</a></h4>
        </div>
        <div class="col-md-12">
            <button id="hide_feeder_btn" class="btn btn-outline-secondary {% if not feed_visible_status %}
            disabled
            {% endif %}" {% if feed_visible_status %}
                    onclick="hide_action('{{ feed_id }}')"
            {% endif %}>Hide
            </button>
            <button id="show_feeder_btn" class="btn btn-outline-info {% if feed_visible_status %}
            disabled
            {% endif %}" {% if not feed_visible_status %}
                    onclick="show_action('{{ feed_id }}')"
            {% endif %}>Show
            </button>
        </div>
        <br><br>
        <div class="col-md-12">
            <h5 class="text-success">Item List({{ number_of_items }})</h5>
            <table id="feeder_items_tb" class="table-bordered">
                <colgroup>
                    <col span="1" style="width: 30%;">
                    <col span="1" style="width: 45%;">
                    <col span="1" style="width: 25%;">
                </colgroup>
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Link</th>
                    <th>View Detail</th>
                </tr>
                </thead>
                <tbody>
                {% for item in item_feed %}
                    <tr>
                        <td><a href="{% url 'home:item' item.id %}">{{ item.title }}</a></td>
                        <td><a href="{{ item.link }}" target="_blank">{{ item.link }}</a></td>
                        <td>
                            <button class="btn btn-primary btn-sm"
                                    onclick="view_item('{{ item.title }}', '{{ item.link }}', '{{ item.description | escapejs }}', '{{ item.embedded }}')">
                                <i class="ti-view-grid"></i></button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="item_modal" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title text-info">Item detail</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <h4>Feeder Name: <br><span id="feed_title" class="auto_break"></span></h4>
                    <h4>Feeder Link: <br><span id="feed_link" class="auto_break"></span></h4>
                    <h5>Item Title: <br><span id="item_title" class="auto_break"></span></h5>
                    <h5>Item Link: <br><span id="item_link" class="auto_break"></span></h5>
                    <h5>Item Description: <br><span id="item_description" class="auto_break"></span></h5>
                    <h5 id="embedded_video" class="auto_break"></h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
        $('#feeder_items_tb').DataTable(
            {
                "order": [[0, "desc"]]
            }
        );

        function view_item(item_title, item_link, item_description, item_embedded) {
            document.getElementById("feed_title").innerText = "{{ feed_title }}";
            document.getElementById("feed_link").innerHTML = "<a href='" + "{{ feed_link }}" + "' target='_blank'>" + "{{ feed_link }}" + "</a>";
            document.getElementById("item_title").innerText = item_title;
            document.getElementById("item_link").innerHTML = "<a href='" + "{{ feed_link }}" + "' target='_blank'>" + item_link + "</a>";
            document.getElementById("item_description").innerHTML = item_description;
            if (item_embedded !== "") {
                document.getElementById("embedded_video").innerHTML = "Embedded Video: " + item_embedded;
            }
            $("#item_modal").modal('show');
        }

        const hide_feeder_btn = $("#hide_feeder_btn");
        const show_feeder_btn = $("#show_feeder_btn");

        function hide_action(feed_id) {
            const res = hide_feeder(feed_id);
            if (res !== 'cancelled') {
                hide_feeder_btn.addClass('disabled');
                hide_feeder_btn.removeAttr('onclick');
                show_feeder_btn.removeClass('disabled');
                show_feeder_btn.attr('onclick', `show_action('${feed_id}')`);
            }
        }

        function show_action(feed_id) {
            const res = show_feeder(feed_id);
            if (res !== 'cancelled') {
                show_feeder_btn.addClass('disabled');
                show_feeder_btn.removeAttr('onclick');
                hide_feeder_btn.removeClass('disabled');
                hide_feeder_btn.attr('onclick', `hide_action('${feed_id}')`);
            }
        }

    </script>
{% endblock %}


miscosas/home/templates/home/feeders.html
{% extends 'root.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/global.css' %}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12">
            {% if feeder_list %}
                <h2 class="text-success">Feeder List</h2>
                <table id="feeders_tb" class="table table-bordered">
                    <colgroup>
                        <col span="1" style="width: 20%;">
                        <col span="1" style="width: 40%;">
                        <col span="1" style="width: 15%;">
                        <col span="1" style="width: 15%;">
                        <col span="1" style="width: 10%;">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Link</th>
                        <th>Number of Items</th>
                        <th>Total Score</th>
                        <th>Visible</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for feeder in feeder_list %}
                        <tr>
                            <td><a href="{% url 'home:feeder' feeder.id %}">{{ feeder.title }}</a></td>
                            <td><a href="{{ feeder.link }}" target="_blank">{{ feeder.link }}</a></td>
                            <td>{{ feeder.item_number }}</td>
                            <td>{{ feeder.score }}</td>
                            <td>
                                {{ feeder.visible_status }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h3 class="text-secondary">There are no feeders to display</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
            $('#feeders_tb').DataTable(
                {
                    "order": [[0, "desc"]]
                }
            );
        });
    </script>
{% endblock %}

miscosas/home/templates/home/items.html
{% extends 'root.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/global.css' %}">
{% endblock %}
{% block content %}
    {% if item_list %}
        <div class="row">
            <div class="col-12">
                <table id="items_tb" class="table table-bordered">
                    <colgroup>
                        <col span="1" style="width: 50%">
                        <col span="1" style="width: 50%;">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Link</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in item_list %}
                        <tr>
                            <td><a href="{% url 'home:item' item.id %}">{{ item.title }}</a></td>
                            <td><a href="{{ item.link }}" target="_blank">{{ item.link }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <h3 class="text-secondary">There are no items to display.</h3>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
            $('#items_tb').DataTable(
                {
                    "order": [[0, "desc"]]
                }
            );
        });
    </script>
{% endblock %}

miscosas/home/templates/home/user.html
{% extends 'root.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/global.css' %}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <h4 class="text-info">Public User Data</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <h5>Name: {{ current_user.username }}</h5>
        </div>
        {% if current_user.id == request.session.id %}
            <div class="col-6">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    Change a photo: <input type="file" name="photo" id="photo" required>
                    <button class="btn btn-sm btn-outline-primary">Submit</button>
                </form>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-12">
            <h4 class="text-info">Change Page Appearance</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <label>Style</label>
            <select name="style" id="style" class="form-control" onchange="change_style()">
                <option value="dark">Dark Mode</option>
                <option value="light">Light Mode</option>
            </select>
        </div>
        <div class="col-6">
            <label>Font Size</label>
            <select name="font_size" id="font_size" class="form-control" onchange="change_font_size()">
                <option value="0.75rem">Small</option>
                <option value="1rem">Normal</option>
                <option value="1.25rem">Large</option>
            </select>
        </div>
    </div>
    <br>
    <h4 class="text-info">List of voted items</h4>
    <div class="row">
        <div class="col-12">
            {% if voted_items %}
                <table id="list_voted_items" class="table  table-bordered">
                    <colgroup>
                        <col span="1" style="width: 50%;">
                        <col span="1" style="width: 50%;">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Link</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in voted_items %}
                        <tr>
                            <td><a href="{% url 'home:item' item.id %}">{{ item.title }}</a></td>
                            <td><a href="{{ item.link }}" target="_blank">{{ item.link }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>There are no voted items.</p>
            {% endif %}
        </div>
    </div>
    <h4 class="text-info">List of commented items</h4>
    <div class="row">
        <div class="col-12">
            {% if commented_items %}
                <table id="list_commented_items" class="table table-bordered">
                    <colgroup>
                        <col span="1" style="width: 35%;">
                        <col span="1" style="width: 35%;">
                        <col span="1" style="width: 30%;">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Link</th>
                        <th>Comment</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in commented_items %}
                        <tr>
                            <td><a href="{% url 'home:item' item.id %}">{{ item.commented_item.title }}</a></td>
                            <td><a href="{{ item.commented_item.link }}"
                                   target="_blank">{{ item.commented_item.link }}</a></td>
                            <td>
                                <button class="btn btn-sm btn-outline-info"
                                        onclick="comment_handle('{{ item.description | escapejs }}')">Click to view
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>There are no commented items.</p>
            {% endif %}
        </div>
    </div>
    <div class="modal fade" id="comment_modal" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title text-info">Comment Text</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <span class="auto_break" id="comment_text"></span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        function comment_handle(text) {
            document.getElementById("comment_text").innerText = text;
            $("#comment_modal").modal('show');
        }

        document.getElementById("style").value = '{{ request.session.style }}';
        document.getElementById("font_size").value = '{{ request.session.font_size }}';

        function change_style() {
            $.ajax(
                {
                    url: '/users/' + "{{ user_id }}" + "/",
                    method: 'POST',
                    data: {
                        flag: 'style'
                    },
                    success: function (result) {
                        const res = result['result'];
                        if (res === 'ok') {
                            window.location.reload();
                        }
                    }
                }
            )
        }

        function change_font_size() {
            const font_size = document.getElementById("font_size").value;
            $.ajax(
                {
                    url: '/users/' + "{{ user_id }}" + "/",
                    method: 'POST',
                    data: {
                        flag: 'font_size',
                        font_size: font_size
                    },
                    success: function (result) {
                        const res = result['result'];
                        if (res === 'ok') {
                            window.location.reload();
                        }
                    }
                }
            )
        }
    </script>
{% endblock %}