miscosas/accounts/api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('retrieve/', ListUsers.as_view()),
    path('register/', RegisterUser.as_view()),
    path('login/', LoginUser.as_view()),
]

miscosas/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', log_in, name='log_in'),
    path('log_out/', log_out, name='log_out'),
]

miscosas/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('xml/', home_xml, name='home_xml'),
    path('feeders/', feeders, name='feeders'),
    path('feeders/<feeder_id>/', feeder, name='feeder'),
    path('items/', items, name='items'),
    path('items/<item_id>/', item, name='item'),
    path('users/', users, name='users'),
    path('users/<user_id>/', user, name='user'),
    path('info/', info, name='info'),
]

miscosas/miscosas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # rest api
    path('api/accounts/', include('accounts.api.urls')),
    path('api/home/', include('home.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miscosas/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='', blank=True)
    voted_item_ids = models.TextField(default='', blank=True)

miscosas/accounts/api/views.py
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from .serializers import *


class ListUsers(APIView):

    def get(self, request):
        usernames = [profile.user.username for profile in Profile.objects.all()]
        return Response(usernames)


class RegisterUser(CreateAPIView):
    serializer_class = ProfileSerializer
    queryset = User.objects.all()


class LoginUser(APIView):
    permission_classes = [AllowAny]
    serializer_class = LoginSerializer
    queryset = User.objects.all()

    def post(self, request):
        data = request.data
        serializer = LoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data['username'], status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

miscosas/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from accounts.models import Profile


def log_in(request):
    template_name = 'accounts/login.html'
    if request.method == 'POST':
        username = request.POST['username']
        psw = request.POST['psw']
        context = {
            'username': username,
            'psw': psw
        }
        # check username validity
        user = User.objects.filter(username=username)
        if not user.exists():
            context["invalid"] = "username"
            return render(request, template_name, context)
        username = user.first().username
        user = authenticate(username=username, password=psw)
        if user is not None:
            login(request, user)
            request.session['id'] = user.id
            profile = Profile.objects.get(user=user)
            try:
                photo_url = profile.photo.url
                request.session['photo_url'] = photo_url
            except Exception as err:
                print(str(err))
                request.session['photo_url'] = 'images/default.png'
            return redirect('home:home')
        else:
            context["invalid"] = "psw"
            return render(request, template_name, context)
    return render(request, template_name)


def log_out(request):
    logout(request)
    return redirect('home:home')

miscosas/templates/accounts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title> MisCosas </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicons -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.jpg' %}"/>
    <!-- Bootstrap CSS File -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- STYLE CSS -->
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
</head>

<body>

{% block content %}
{% endblock %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

miscosas/templates/root.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title> MisCosas </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Favicons -->
    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/favicon.jpg' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% block css %}
    {% endblock %}
</head>

<body id="body">
<header id="header">
    <div class="container-fluid">

        <div id="logo" class="pull-left">
            <img src="{% static 'images/banner.jpg' %}"
                 alt="">
            <div class="d-inline-flex">
                <span>MisCosas</span>
            </div>
        </div>

        <nav id="nav-menu-container">
            <ul class="nav-menu">
                {% if request.session.id %}
                    <li class="dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                            {% if request.session.photo_url == 'images/default.png' %}
                                <img src="{% static request.session.photo_url %}" alt="">
                            {% else %}
                                <img src="{{ request.session.photo_url }}" alt="">
                            {% endif %}
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item" href="{% url 'home:user' request.session.id %}">
                                <i class="ti-user text-secondary mr-2"></i>Profile
                            </a>
                            <a class="dropdown-item" href="{% url 'accounts:log_out' %}">
                                <i class="ti-power-off text-secondary mr-2"></i>Logout
                            </a>
                        </div>
                    </li>
                {% else %}
                    <li class="dropdown">
                        <a href="{% url 'accounts:log_in' %}">
                            <button class="btn btn-sm btn-outline-light px-4 py-1">
                                Sign in
                            </button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>
<main id="main">
    <div id="menu">
        <div class="container-fluid py-3">
            <div class="row">
                <div class="col-6">
                    <div class="row">
                        <div class="col-9">
                            <p id="current-menu" class="text-capitalize">
                                {{ current_menu }}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="row">
                        <div class="{% if request.session.id %}
                        col-3
                        {% else %}
                        col-4
                        {% endif %}"></div>
                        <div class="{% if request.session.id %}
                        col-9
                        {% else %}
                        col-8
                        {% endif %}">
                            <ul id="subnav">
                                <li>
                                    <a href="{% url 'home:home' %}">
                                        Home
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'home:feeders' %}">
                                        Feeders
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'home:items' %}">
                                        Items
                                    </a>
                                </li>
                                {% if request.session.id %}
                                    <li>
                                        <a href="{% url 'home:users' %}">
                                            Users
                                        </a>
                                    </li>
                                {% endif %}
                                <li>
                                    <a href="{% url 'home:info' %}">
                                        Information
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="main-content">
        <div class="col-12 px-0">
            <div class="col-11 mx-auto my-5">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</main>
<footer class="text-secondary">
    This application uses data provided by Youtube Channel and Subreddit.
</footer>

<!-- JavaScript Libraries -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/counterup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/lightbox.min.js' %}"></script>
<script src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
<script id="csrf_token">
    {# getting csrf token #}
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                // Only send the token to relative URLs i.e. locally.
                xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
            }
        }
    });

    function perform_style() {
        document.getElementById("body").style.backgroundColor = '{{ request.session.style }}' === 'dark' ? "rgba(95, 95, 95, 0.3)" : "";
    }

    function perform_font_size() {
        document.getElementById("body").style.fontSize = '{{ request.session.font_size }}';
    }

    perform_style();
    perform_font_size();

    function hide_feeder(feeder_id) {
        if (confirm("Are you sure?")) {
            $.ajax(
                {
                    url: '{% url 'home:home' %}',
                    method: 'POST',
                    data: {
                        flag: 'hide_feeder',
                        feeder_id: feeder_id
                    },
                    success: function (result) {
                        return result['result'];
                    }
                }
            );
        } else {
            return 'cancelled';
        }
    }

    function show_feeder(feeder_id) {
        if (confirm("Are you sure?")) {
            $.ajax(
                {
                    url: '{% url 'home:home' %}',
                    method: 'POST',
                    data: {
                        flag: 'show_feeder',
                        feeder_id: feeder_id
                    },
                    success: function (result) {
                        return result['result'];
                    }
                }
            );
        } else {
            return 'cancelled';
        }
    }

</script>
{% block javascript %}
{% endblock %}
</body>
</html>